In [1]:
import numpy as np

In [2]:
class ActiveFunction:

    class Sigmoid():

        @staticmethod
        def evaluat(array: np.ndarray) -> np.ndarray:
            return 1 / (1 + np.exp(-array))

        @staticmethod
        def derivative(array: np.ndarray) -> np.ndarray:
            temp = np.exp(-array)
            return temp / np.power((1 + temp), 2)

    class tanh():

        @staticmethod
        def evaluat(array: np.ndarray) -> np.ndarray:
            return np.tanh(array)

        @staticmethod
        def derivative(array: np.ndarray) -> np.ndarray:
            return 1 - np.power(np.tanh(array), 2)

In [3]:
class Layer():

    def __init__(self, size: int, previous: int, active: ActiveFunction) -> None:
        self.bias = np.random.randn(size, 1)
        self.weights = np.random.randn(size, previous)
        self.active = active

    def stepForward(self, input: np.ndarray) -> np.ndarray:
        self.lastInput = input
        temp = []
        for weight in self.weights:
            temp.append(np.sum(input * weight))
        self.lastOut = self.active.evaluat((np.array(temp).reshape(self.bias.shape) + self.bias).T)
        return self.lastOut
    
    def layerLastCost(self, expectedOut: np.ndarray) -> np.ndarray:
        cost1 = 2 * (expectedOut - self.lastOut)
        cost2 = self.active.derivative(self.lastOut)
        self.cost = cost1 * cost2
        return self.cost
    
    def layerCost(self, nextLayerCost: np.ndarray) -> np.ndarray:
        cost1 = self.weights
        cost2 = self.active.derivative(self.lastOut)
        self.cost = cost1 * cost2 * nextLayerCost
        return self.cost
    
    def fit(self):
        ...

class MyNN:
    
    def __init__(self, shape: list, active: ActiveFunction, learningrate: float = 0.02) -> None:
        layers = []
        for i in range(1, len(shape)):
            layers.append(Layer(shape[i], shape[i - 1], active))
        self.layers = layers
        self.inputSize = shape[0]
        self.outputSize = shape[-1]
        self.active = active
        self.lr = learningrate
    
    def forWard(self, input: np.ndarray) -> np.ndarray:
        for layer in self.layers:
            input = layer.stepForward(input)
        return input
    
    def getLost(self, predictOut: np.ndarray, trueOut: np.ndarray) -> np.ndarray:
        return np.sum(np.power(predictOut - trueOut, 2))

    def backWard(self):
        ...

In [4]:
a = np.array([0, -2, 1])
b = np.array([[2, 3, 4], [1, 2 ,3]])
c = np.array([2, 4])

In [249]:
q = []
for z in b:
    q.append(np.sum(a * z))
ActiveFunction.Sigmoid.evaluat((np.array([q]).reshape(c.shape) + c).T)

array([0.99999386, 0.9999833 ])

In [250]:
v = Layer(2, 3, ActiveFunction.Sigmoid)
v.bias = c
v.weights = b

In [251]:
v.step(a)

array([0.99999386, 0.9999833 ])

In [17]:
n = MyNN([3, 2], ActiveFunction.Sigmoid)
print(n.layers[0].weights)
print(n.layers[0].bias)


[[-0.2503979   0.1847132  -0.20466251]
 [-0.65959198 -1.74009604  0.28733756]]
[[-0.92757288]
 [-0.3428947 ]]


In [18]:
n.forWard(np.array([10, 10, 10]))
n.layers[0].layerLastCost(np.array([1, 1]))

array([[0.48701644, 0.5       ]])

In [421]:
tar = np.array([1, 2])
print(n.forward(a))
n.getLost(n.forward(a), tar)


[[0.50052149 0.13682897]]


3.7208850781170346

In [392]:
ActiveFunction.Sigmoid.evaluat(-100)

3.7200759760208356e-44

In [21]:
np.array([[1, 2]]) * np.array([2, 3, 4])

ValueError: operands could not be broadcast together with shapes (1,2) (3,) 